package cn.org.cfpamf.data.sql.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cn.org.cfpamf.data.sql.db.Baidu;

import cn.org.cfpamf.data.sql.dao.BaiduDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig baiduDaoConfig;

    private final BaiduDao baiduDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baiduDaoConfig = daoConfigMap.get(BaiduDao.class).clone();
        baiduDaoConfig.initIdentityScope(type);

        baiduDao = new BaiduDao(baiduDaoConfig, this);

        registerDao(Baidu.class, baiduDao);
    }
    
    public void clear() {
        baiduDaoConfig.getIdentityScope().clear();
    }

    public BaiduDao getBaiduDao() {
        return baiduDao;
    }

}
