package cn.org.cfpamf.data.sql.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END
/**
 * Entity mapped to table "BAIDU".
 */
public class Baidu implements Parcelable {

    private String id;
    /** Not-null value. */
    private String response;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Baidu() {
    }

    public Baidu(String id) {
        this.id = id;
    }

    public Baidu(String id, String response) {
        this.id = id;
        this.response = response;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getResponse() {
        return response;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setResponse(String response) {
        this.response = response;
    }

    // KEEP METHODS - put your custom methods here
    //下次不会被覆盖
    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.id);
        dest.writeString(this.response);
    }

    protected Baidu(Parcel in) {
        this.id = in.readString();
        this.response = in.readString();
    }

    public static final Parcelable.Creator<Baidu> CREATOR = new Parcelable.Creator<Baidu>() {
        public Baidu createFromParcel(Parcel source) {
            return new Baidu(source);
        }

        public Baidu[] newArray(int size) {
            return new Baidu[size];
        }
    };
    // KEEP METHODS END

}
